# Generated by Django 3.1.6 on 2021-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='hellooo', max_length=30)),
                ('symbol', models.CharField(default=12, max_length=30)),
                ('market', models.CharField(blank=True, max_length=30, null=True)),
                ('stok_type', models.CharField(blank=True, max_length=1, null=True)),
                ('size', models.DecimalField(decimal_places=5, max_digits=16)),
                ('open', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
            ],
        ),
    ]
