# Generated by Django 3.1.7 on 2021-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(default=12, max_length=30)),
                ('market', models.CharField(max_length=30, null=True)),
                ('stok_type', models.CharField(max_length=1, null=True)),
                ('size', models.DecimalField(decimal_places=5, max_digits=16)),
                ('open', models.DateField(null=True)),
                ('low', models.DecimalField(decimal_places=5, max_digits=16, null=True)),
                ('high', models.DecimalField(decimal_places=5, max_digits=16, null=True)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=16, null=True)),
                ('volum', models.IntegerField(null=True)),
            ],
        ),
    ]
